### ISSUE TITLE
    model_checkpoint_path = ckpt.model_checkpoint_path AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by prraoo** [yanbeic/semi-memory#3]
Hi,v@yanbeic Thank for the code. 

While running CIFAR10 bash script I am facing the following issue: 

> model_checkpoint_path = ckpt.model_checkpoint_path
> AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

Could you help me out?

**Comment by yanbeic** [comment]
Hi,

This error is caused by test.py line 46.
It generally happens when the model is not saved properly.

For example, if your the path  `FLAGS.checkpoint_path` is either _empty_ or _referring to a wrong position_.

Hope this can help you.

**Comment by prraoo** [comment]
@yanbeic thank you for the quick response. 

Yes I felt the same. Within checkpoint folder I have something like this:
> ls /semi-memory/results/cifar10/semi_split1/
> events.out.tfevents.1549981282.somabiswaspc

Is it this correct? My familiarity with tensorflow is bit limited. Any suggestions from your would be of great help. Thanks

**Comment by yanbeic** [comment]
Hi,

Besides your event file, you should also find something as follows:
`checkpoint model.ckpt-499.data-00000-of-00001  model.ckpt-499.index  model.ckpt-499.meta`,
which is the saved model.

**Comment by prraoo** [comment]
I will be working these suggestions, for now, it looks like a bug from my end. Will reopen if necessary. 

Thank you
